apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
      - name: quote-app
        image: 141409473062.dkr.ecr.us-east-1.amazonaws.com/quote-app:v1
        ports:
        - containerPort: 80
